version: '3.9'
services:
  school-database:
    build:
      context: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school
    volumes:
      - scl-db-vol:/var/lib/postgresql/data
volumes:
  scl-db-vol: